target 'iosApp' do
   use_modular_headers!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
       if target.name == "gs_pos_ios-UI-UITests"
           config.build_settings['TEST_TARGET_NAME'] = "iosApp"
       end
     end
   end
end